version: "3.5"
services:
  jellyfin-app:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin-app
    ## FOR HARDWARE ACCELERATION
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ## END FOR HARDWARE ACCELERATION
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ${JELLYFIN_CACHE}:/cache
      - ${JELLYFIN_MEDIA}:/media
      - ${JELLYFIN_VIDEO_EDITS}:/video_edits
    restart: "unless-stopped"
    environment:
      - JELLYFIN_PublishedServerUrl=${SITE_URL}
    labels:
      - flame.type=application
      - flame.name=Jellyfin
      - flame.url=${SITE_URL}
      - flame.category=Medias
      - flame.icon=multimedia
    networks:
      - production_jellyfin

volumes:
    jellyfin_cache:
        name: ${JELLYFIN_CACHE}
        external: false
    jellyfin_media:
        name: ${JELLYFIN_MEDIA}
        external: false

networks:
    production_jellyfin:
      driver: bridge